package com.hua.dao;

import com.hua.domain.Employee;
import java.util.List;

public interface IEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String manager);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_employee
     *
     * @mbg.generated
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_employee
     *
     * @mbg.generated
     */
    Employee selectByPrimaryKey(String manager);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_employee
     *
     * @mbg.generated
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Employee record);
}