package com.hua.dao;

import com.hua.domain.LeaveBill;
import java.util.List;

public interface ILeaveBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_leavebill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_leavebill
     *
     * @mbg.generated
     */
    int insert(LeaveBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_leavebill
     *
     * @mbg.generated
     */
    LeaveBill selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_leavebill
     *
     * @mbg.generated
     */
    List<LeaveBill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_leavebill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LeaveBill record);
}