package com.hua.dao;

import com.hua.domain.Role;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface IRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);

	List<Role> getAllRolesByLimit(@Param("pageIndex")Integer pageIndex, @Param("pageSize")Integer pageSize);
}