package com.hua.dao;

import com.hua.domain.User;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface IUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

	User isLogin(@Param("userName")String userName,@Param("passWord") String passWord);

	List<User> getUserListByLimit(@Param("pageIndex")Integer pageIndex, @Param("pageSize")Integer pageSize);

	int delete_user_statusByUserId(@Param("userId")int userId, @Param("status")int status);

}