package com.hua.dao;

import com.hua.domain.UserRole;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("roleId") Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    List<UserRole> selectAll();

	List<UserRole> findRoleByUserId(@Param("userId")String userId);

	int deleteRoleByUserId(@Param("userId")String userId);

}