package com.hua.domain;

import java.util.Date;

public class LeaveBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.days
     *
     * @mbg.generated
     */
    private String days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.leavedate
     *
     * @mbg.generated
     */
    private Date leavedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_leavebill.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.user_id
     *
     * @return the value of a_leavebill.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.user_id
     *
     * @param userId the value for a_leavebill.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.id
     *
     * @return the value of a_leavebill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.id
     *
     * @param id the value for a_leavebill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.days
     *
     * @return the value of a_leavebill.days
     *
     * @mbg.generated
     */
    public String getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.days
     *
     * @param days the value for a_leavebill.days
     *
     * @mbg.generated
     */
    public void setDays(String days) {
        this.days = days == null ? null : days.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.content
     *
     * @return the value of a_leavebill.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.content
     *
     * @param content the value for a_leavebill.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.remark
     *
     * @return the value of a_leavebill.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.remark
     *
     * @param remark the value for a_leavebill.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.leavedate
     *
     * @return the value of a_leavebill.leavedate
     *
     * @mbg.generated
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.leavedate
     *
     * @param leavedate the value for a_leavebill.leavedate
     *
     * @mbg.generated
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_leavebill.state
     *
     * @return the value of a_leavebill.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_leavebill.state
     *
     * @param state the value for a_leavebill.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}